//
// Created by psc on 2022/2/24.
//

#ifndef Mbed_Generator_WAIT_TEMPLATE_H
#define Mbed_Generator_WAIT_TEMPLATE_H

#include <string>

std::string wait_h_template = R"(// Generated by Shichen Peng @ Glasgow College UESTC
// For Microelectronic System Course Use Only

void wait_ms(unsigned int ms);

void wait_s(float s);

)";

std::string wait_cpp_template = R"(// Generated by Shichen Peng @ Glasgow College UESTC
// For Microelectronic System Course Use Only

#include "platform/mbed_thread.h"
#include "wait.h"

void wait_ms(unsigned int ms)
{
    thread_sleep_for(ms);
}

void wait_s(float s)
{
    thread_sleep_for((unsigned int)(1000 * s));
}

)";

#endif //Mbed_Generator_WAIT_TEMPLATE_H
