//
// Created by psc on 2022/2/23.
//

#ifndef Mbed_Generator_MAIN_TEMPLATE_H
#define Mbed_Generator_MAIN_TEMPLATE_H

#include <iostream>

std::string main_template = R"(// Generated by Shichen Peng @ Glasgow College UESTC
// For Microelectronic System Course Use Only

#include "mbed.h"
#include "wait.h"

int main()
{
    // Initialise the digital pin LED1 as an output
    DigitalOut led(LED1);

    while (true)
    {
        led = !led;
        wait_ms(500);
    }
    return 0;
}

)";

#endif //Mbed_Generator_MAIN_TEMPLATE_H
